[package]
name = "radio-shack-scale"
version = "0.1.0"
authors = ["Carlos Correa <cgc@stanford.edu>"]
edition = "2021"
rust-version = "1.65"

[dependencies]
egui = "0.20.1"
eframe = "0.20.1"
hidapi = "1.1.0"
tracing-subscriber = "0.3"
