[package]
name = "rust-chip8"
version = "0.1.0"
authors = ["Carlos Correa <cgcorrea@princeton.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.120.0"
image = "0.23.14"
rand = "0.8.3"
